kind: Namespace
apiVersion: v1
metadata:
  name: ticketmaster
---
kind: Service
apiVersion: v1
metadata:
  name: tm-testy-se
  namespace: ticketmaster
  labels:
    app: tm-testy-se
spec:
  type: NodePort
  selector:
    app: tm-testy-se
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tm-testy-se
  namespace: ticketmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-testy-se
  template:
    metadata:
      labels:
        app: tm-testy-se
        version: v1
    spec:
      containers:
        - name: tm-testy-se
          image: tm-testy-se
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
---
